FROM php:7.2-apache

RUN apt-get update

# 1. Developpement
RUN apt-get install -y \
    git \
    zip \
    curl \
    sudo \
    unzip \
    libicu-dev \
    libbz2-dev \
    libpng-dev \
    libjpeg-dev \
    libmcrypt-dev \
    libreadline-dev \
    libfreetype6-dev \
    g++

# 2. Configurations Apache et Routage de l'application Web
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# 3. 'mod_rewrite' pour l'URL rewrite et 'mod_headers' pour les extras headers '.htaccess' comme 'Access-Control-Allow-Origin-'
RUN a2enmod rewrite headers

# 4. Démarrer avec la base de configuration php puis après ajouter les extensions
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

RUN docker-php-ext-install \
    bz2 \
    intl \
    iconv \
    bcmath \
    opcache \
    calendar \
    mbstring \
    pdo_mysql \
    zip

# 5. Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# 6. Nous avons besoin d'un utilisateur avec le même UID/GID comme 'host user'
# Ainsi, lorsque nous exécutons des commandes CLI, tous les droits de propriété du fichier hôte restent intacts
# Sinon, la commande depuis l'intérieur du conteneur créera des fichiers et des répertoires appartenant à la racine
ARG uid
RUN useradd -G www-data,root -u $uid -d /home/devuser devuser
RUN mkdir -p /home/devuser/.composer && \
    chown -R devuser:devuser /home/devuser
